export const funnelEvents = [
  "view_home",
  "view_pricing",
  "view_pricing_changes",
  "view_provider_pricing",
  "view_compare",
  "view_atlas",
  "view_library",
  "view_lab",
  "view_account",
  "view_dashboard",
  "view_settings",
  "view_audit",
  "view_ledger",
  "view_attribution_guide",
  "view_budget_guide",
  "view_service_attribution",
  "view_service_budget_guard",
  "cta_account",
  "cta_pricing",
  "cta_atlas",
  "cta_lab",
  "cta_audit",
  "cta_ledger",
  "audit_report_copy",
  "audit_report_download",
  "cta_audit_service",
  "cta_service_attribution",
  "cta_service_budget_guard",
  "cta_service_email",
  "cta_service_attribution_email",
  "cta_service_attribution_telegram",
  "cta_service_attribution_github",
  "cta_budget_guide_service",
  "cta_service_budget_guard_email",
  "cta_service_budget_guard_telegram",
  "cta_service_budget_guard_github",
  "service_attribution_enquiry_sent",
  "service_budget_guard_enquiry_sent",
  "lab_run_attempt",
  "lab_run_success",
  "lab_run_failed",
  "account_signup_attempt",
  "account_signin_attempt",
  "account_reset_attempt",
  "checkout_created",
  "checkout_cancelled",
  "checkout_failed",
] as const;

export type FunnelEvent = (typeof funnelEvents)[number];

const allowedEvents = new Set<string>(funnelEvents);

export function isFunnelEvent(value: unknown): value is FunnelEvent {
  return typeof value === "string" && allowedEvents.has(value);
}
